Scelta razza, classe e background. Scelta del lancio dei dadi o Point buy

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,6 +1,10 @@
 #!/bin/bash
 
 echo "Compiling..."
-g++ ./src/main.cpp -o dnd_generator $(pkg-config --cflags --libs gtk4 libadwaita-1)
-echo "Running..."
-./dnd_generator
+if g++ ./src/main.cpp -o dnd_generator $(pkg-config --cflags --libs gtk4 libadwaita-1); then
+    echo "Compilation successful. Running..."
+    ./dnd_generator > /dev/null # 2>&1
+else
+    echo "Compilation failed. The program will not be run." 
+    exit 1
+fi
